java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingWriteLockRecipe localhost:2181 /sample-lock A &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingBlockingWriteLock localhost:2181 /sample-lock B &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingDistributedOperation localhost:2181 /sample-lock C &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingWriteLockRecipe localhost:2181 /sample-lock D &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingBlockingWriteLock localhost:2181 /sample-lock E &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingDistributedOperation localhost:2181 /sample-lock F &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingWriteLockRecipe localhost:2181 /sample-lock G &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingBlockingWriteLock localhost:2181 /sample-lock H &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingDistributedOperation localhost:2181 /sample-lock I &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingWriteLockRecipe localhost:2181 /sample-lock J &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingBlockingWriteLock localhost:2181 /sample-lock K &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingDistributedOperation localhost:2181 /sample-lock L &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingWriteLockRecipe localhost:2181 /sample-lock M &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingBlockingWriteLock localhost:2181 /sample-lock N &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingDistributedOperation localhost:2181 /sample-lock O &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingWriteLockRecipe localhost:2181 /sample-lock P &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingBlockingWriteLock localhost:2181 /sample-lock Q &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingDistributedOperation localhost:2181 /sample-lock R &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingWriteLockRecipe localhost:2181 /sample-lock S &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingBlockingWriteLock localhost:2181 /sample-lock T &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingDistributedOperation localhost:2181 /sample-lock U &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingWriteLockRecipe localhost:2181 /sample-lock V &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingBlockingWriteLock localhost:2181 /sample-lock W &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingDistributedOperation localhost:2181 /sample-lock X &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingWriteLockRecipe localhost:2181 /sample-lock Y &
java -cp ../../target/classes:../../etc/examples-libs/* com.nearinfinity.examples.zookeeper.lock.WorkerUsingBlockingWriteLock localhost:2181 /sample-lock Z &
